server:
  port:  8762
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8080/eureka/
spring:
  application:
    name:  member
  redis:
    host: 10.10.35.183
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
#     数据库连接信息 
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/shop
        username: root
        password: root
        #       使用druid数据源
        type:  com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters:  stat
        max-active: 20
        initial-size: 1
        maxWait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
#       activemq连接信息
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
#     队列
  messages:
    queue:  mail_queue
